language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
            - libfftw3-dev
            - libncursesw5-dev
            - libpulse-dev
      before_install:
        - export CXX=clang++-3.7
        - export CC=clang-3.7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libfftw3-dev
            - libncursesw5-dev
            - libpulse-dev
      before_install:
        - export CXX=g++-4.9
        - export CC=gcc-4.9

    - os: osx
      before_install:
        - brew update
        - brew tap homebrew/dupes && brew install fftw ncurses
